config/routes.rb
Rails.application.routes.draw do
  
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :uploads
  resources :galleries
  resources :paintings

  root  'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contacts', to: 'static_pages#contacts', via: 'get'
  match '/artgallery',  to: 'artgallery#artgallery',  via: 'get'
  match '/allgallery',  to: 'artgallery#all',  via: 'get'
  match '/images',  to: 'image#new',  via: 'get'
   

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  # attr_accessible :name
  has_many :paintings
    private
  ## Strong Parameters 
  def gallery_params
    params.require(:gallery).permit(:name)
  end
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  # attr_accessible :gallery_id, :name, :image, :remote_image_url
  belongs_to :gallery
  mount_uploader :image, ImageUploader
  
  private
  ## Strong Parameters 
  def image_params
    params.require(:painting).permit(:gallery_id, :name, :image, :remote_image_url)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artgallery_controller.rb
class ArtgalleryController < ApplicationController
  def artgallery
    if params[:id]
      @gallery = Gallery.find(params[:id])
      @paintings = @gallery.paintings
    else
      @paintings = Painting.all      
    end
  end
  

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate
  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
    @gallery = Gallery.new
  end
  
 def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      flash[:notice] = "Successfully created gallery."
      redirect_to @gallery
    else
      render :action => 'new'
    end
  end


  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update_attributes(params[:gallery])
      flash[:notice] = "Successfully updated gallery."
      redirect_to gallery_url
    else
      render :action => 'edit'
    end
  end

  def destroy
     @gallery = Gallery.find(params[:id])
     @gallery.destroy
     # @gallery.destroy
    flash[:success] = "Successfully destroyed gallery."
    redirect_to galleries_url
  end  
    
  private
  ## Strong Parameters 
  def gallery_params
    params.require(:gallery).permit(:name)
  end
   def authenticate
      authenticate_or_request_with_http_basic do |name, password|
         name == "admin" &&  password == "secret"
      end
    end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
   before_action :authenticate
  def new
    @painting = Painting.new(:gallery_id => params[:gallery_id])
  end

  def create
    @painting = Painting.new(painting_params)
    if @painting.save
      flash[:notice] = "Successfully created painting."
      redirect_to @painting.gallery
    else
      render :action => 'new'
    end
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      flash[:notice] = "Successfully updated painting."
      redirect_to @painting.gallery
    else
      render :action => 'edit'
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    flash[:notice] = "Successfully destroyed painting."
    redirect_to @painting.gallery
  end
  
  
  private
  ## Strong Parameters 
  def painting_params
    params.require(:painting).permit(:gallery_id, :name, :image, :remote_image_url)
  end
  def authenticate
       authenticate_or_request_with_http_basic do |name, password|
       name == "admin" &&  password == "secret"
    end
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def galleries
  end

  def about
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def galleries()
     galleries = Gallery.all
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/gall_helper.rb
module GallHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/artgallery/artgallery.html.erb
<div id="page">
	<div id="container">
		<h1>Галерея</h1>
		<div id="gallery" class="content">
			<div id="controls" class="controls"></div>
			<div class="slideshow-container">
				<div id="loading" class="loader"></div>
				<div id="slideshow" class="slideshow"></div>
			</div>
			<div id="caption" class="caption-container"></div>
		</div>
		
		<div id="thumbs" class="navigation">
			<ul class="thumbs noscript">
				  <%= render @paintings %>
			</ul>
		</div>
		<div style="clear: both;"></div>
	</div>
</div>

	<!--%= image_tag("slider/3.jpg", alt:"image") %>
	<%= image_tag("slider/1.jpg", alt:"image") %>
	<%= image_tag("slider/2.jpg", alt:"image") %>
	<%= link_to image_tag("9.jpg", alt:"image")%-->
<script type="text/javascript">
			jQuery(document).ready(function($) {
				// We only want these styles applied when javascript is enabled
				$('div.navigation').css({'width' : '300px', 'float' : 'left'});
				$('div.content').css('display', 'block');

				// Initially set opacity on thumbs and add
				// additional styling for hover effect on thumbs
				var onMouseOutOpacity = 0.67;
				$('#thumbs ul.thumbs li').opacityrollover({
					mouseOutOpacity:   onMouseOutOpacity,
					mouseOverOpacity:  1.0,
					fadeSpeed:         'fast',
					exemptionSelector: '.selected'
				});
				
				// Initialize Advanced Galleriffic Gallery
				var gallery = $('#thumbs').galleriffic({
					delay:                     2500,
					numThumbs:                 15,
					preloadAhead:              10,
					enableTopPager:            true,
					enableBottomPager:         true,
					maxPagesToShow:            7,
					imageContainerSel:         '#slideshow',
					controlsContainerSel:      '#controls',
					captionContainerSel:       '#caption',
					loadingContainerSel:       '#loading',
					renderSSControls:          true,
					renderNavControls:         true,
					playLinkText:              'Play Slideshow',
					pauseLinkText:             'Pause Slideshow',
					prevLinkText:              '&lsaquo; Previous Photo',
					nextLinkText:              'Next Photo &rsaquo;',
					nextPageLinkText:          'Next &rsaquo;',
					prevPageLinkText:          '&lsaquo; Prev',
					enableHistory:             false,
					autoStart:                 false,
					syncTransitions:           true,
					defaultTransitionDuration: 900,
					onSlideChange:             function(prevIndex, nextIndex) {
						// 'this' refers to the gallery, which is an extension of $('#thumbs')
						this.find('ul.thumbs').children()
							.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
							.eq(nextIndex).fadeTo('fast', 1.0);
					},
					onPageTransitionOut:       function(callback) {
						this.fadeTo('fast', 0.0, callback);
					},
					onPageTransitionIn:        function() {
						this.fadeTo('fast', 1.0);
					}
				});
			});
</script>

app/views/galleries/_form.html.erb
<%= form_for @gallery do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/galleries/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @gallery %> |
  <%= link_to "View All", galleries_path %>
</p>

app/views/galleries/index.html.erb
<% for gallery in @galleries %>
  <div class="gallery">
    <h2><%= link_to gallery.name, gallery %></h2>
    Paintings: <%= gallery.paintings.size %>
  </div>
<% end %>

<p><%= link_to "New Gallery", new_gallery_path %></p>

app/views/galleries/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", galleries_path %></p>

app/views/galleries/show.html.erb
<div id="paintings">
  <% for painting in @gallery.paintings %>
    <div class="painting">
      <%= image_tag painting.image %>
      <div class="name"><%= painting.name %></div>
      <div class="actions">
        <%= link_to "редагувати", edit_painting_path(painting) %> |
        <%= link_to "видалити", painting, data: { confirm: "Ви впевнені?"}, method: :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

<p>
  <%= link_to "Додати картини", new_painting_path(:gallery_id => @gallery) %> |
  <%= link_to "Видалити Галерею", @gallery, method: :delete, data: { confirm: "Видалити галерею? Ви впевнені?" } %> |
  <%= link_to "Перейти до Галерей", galleries_path %>
</p>

app/views/image/create.js.erb
<% if @image.new_record? %>
  alert("Failed to upload image: <%= j @image.errors.full_messages.join(', ').html_safe %>");
<% else %>
  alert("adding images");
  $("#images").append("<%= j render(@image) %>");
<% end %>

app/views/image/new.html.erb
<!-- <div class="files"> 
	<%= form_for @image, :html => { :class => "image", :multipart => true } do |f| %>
	  <%= f.file_field :picture %>
	  <div>Upload files</div>
	<% end %>
	
	<table class="upload_files"></table>
	<table class="download_files"></table>
</div> -->


<div id="images">
	<%= render @images %>	
</div>

<div class="clear"></div>


<%= form_for Image.new  do |f| %>
	<%= f.label :image, "Upload image:" %>
	<%= f.file_field :image, multiple: true , name: "image[image]" %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
	<div class="upload">
		{%=0.name%}
		<div class="progress">
			<div class="bar" style="width: 0%"></div>	
		</div>
	</div>
</script>
	<!-- 
<script type="text/javascript" charset="utf-8"> 
   $(function () {
  $('.upload').fileUploadUI({
        uploadTable: $('.upload_files'),
        downloadTable: $('.download_files'),
        buildUploadRow: function (files, index) {
            var file = files[index];
            return $('<tr><td>' + file.name + '<\/td>' +
                    '<td class="file_upload_progress"><div><\/div><\/td>' +
                    '<td class="file_upload_cancel">' +
                    '<div class="ui-state-default ui-corner-all ui-state-hover" title="Cancel">' +
                    '<span class="ui-icon ui-icon-cancel">Cancel<\/span>' +
                    '<\/div><\/td><\/tr>');
        },
        buildDownloadRow: function (file) {
            return $('<tr><td><img alt="Photo" width="40" height="40" src="' + file.pic_path + '">' + file.name + '<\/td><\/tr>');
        },
    });
});
</script> -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   (c) nataliart.com.ua 2014
   </small>
  <nav>
    <ul>
      <li><%= link_to "Про мене",    about_path %></li>
      <li><%= link_to "Контакти", contacts_path %></li>
 	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="wide">
		
	</div>
	<div class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "NataliArt", root_path, id: "logo" %>
	  			<nav>
					<ul class="nav pull-right">
					  <li><%= link_to "Домівка",  root_path %></li>
					  <li id="fat-menu" class="dropdown">
              			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
               				 Галерея <b class="caret"></b>
              			</a>
              			<% @galleriess = galleries %>
						<ul class="dropdown-menu">
			                <% for gallery in @galleriess %>
			                	 <li><%= link_to gallery.name, artgallery_path(:id => gallery.id) %></li> 
			                <% end %>
			                <li class="divider"></li>
			                <li><%= link_to "Усі", artgallery_path %> </li>
	             		</ul>
					 </li>
					  <li><%= link_to "Про мене",    about_path %></li>
					  <li><%= link_to "Контакти", contacts_path %></li>
					</ul>
				</nav>
			</div>        
	  	</div>
  	</div>	
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" 
  "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
  	 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
     <title><%= yield(:title)%></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>   
   	<script data-turbolinks-track="true" src="/assets/mobilyslider.js?body=1"></script>
	<link data-turbolinks-track="true" href="/assets/slider.css?body=1" media="all" rel="stylesheet" />
	<script data-turbolinks-track="true" src="/assets/jquery.galleriffic.js?body=1"></script>
	<link data-turbolinks-track="true" href="/assets/galleries/galleriffic-2.css?body=1" media="all" rel="stylesheet" />
	<link data-turbolinks-track="true" href="/assets/galleries/jush.css?body=1" media="all" rel="stylesheet" />
	<link data-turbolinks-track="true" href="/assets/galleries/white.css?body=1" media="all" rel="stylesheet" />
	<script data-turbolinks-track="true" src="/assets/jquery.opacityrollover.js?body=1"></script>
<%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>    
    <div class="container b box shadows">
     	 <%= yield %>
    </div>
    <div class="container">
    	<%= render 'layouts/footer' %>
    </div>
    
  </body>
  
</html>

app/views/paintings/_form.html.erb
<%= form_for @painting, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :gallery_id %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/paintings/_painting.html.erb
<li>
	<%= link_to (image_tag painting.image), painting.image.url, class: "thumb",  name: "optionalCustomIdentifier" %>
	<div class="caption">
		<div class="image-title"><%= painting.name %></div>
		<div class="image-desc">Description</div>
	</div>
</li>

app/views/paintings/edit.html.erb
<%= render 'form' %>

<p><%= link_to "Back to Gallery", @painting.gallery %></p>

app/views/paintings/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to Gallery", @painting.gallery %></p>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contacts.html.erb
<h1>StaticPages#contacts</h1>
<p>Find me in app/views/static_pages/contacts.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

	
	 <div class="slider">
        <div class="sliderContent">
            <div class="item"><%= image_tag("10.jpg", alt:"image") %></div>
		    <div class="item"><%= image_tag("slider/3.jpg", alt:"image") %></div>
		    <div class="item"><%= image_tag("slider/1.jpg", alt:"image") %></div>
		    <div class="item"><%= image_tag("slider/2.jpg", alt:"image") %></div>
		    <div class="item"><%= link_to image_tag("9.jpg", alt:"image")%></div>
		</div>
	</div>
		
	<div class="row">	
				
		  <div class="span4 center">
		  	<h4>Копії</h4>
		  	<%= link_to image_tag("bottom_gal/copy.jpg", alt:"image"), artgallery_path %> 
		  </div>
		  <div class="span4 center">
		  	<h4>Портрети</h4>
		  		<%= link_to image_tag("bottom_gal/portret.jpg", alt:"image"), artgallery_path %> 
		  </div>
		   <div class="span4 center">
		  	<h4>Живопис</h4>
		  	<%= link_to image_tag("bottom_gal/painting.jpg", alt:"image"), artgallery_path %>
		  </div>
		</div>

<script>
  $('.slider').mobilyslider({
        animationSpeed: 500,
        autoplay: true,
        autoplaySpeed: 3000,
        pauseOnHover: true,
        bullets: true, 
   		arrows: true,
   		arrowsHide: true
   		//transition: 'fade'
    });

</script>